### ISSUE TITLE
Not working with node 14.* anymore

### ISSUE THREAD

**Issue by emilas44** [thecodercoder/gulp-browsersync#1]
Can you please fix it and explain why it didn't work?

Node version used: 14.15.4 and 15.6.0
npm version used: 6.14.10 and 7.4

Steps to reproduce...
0. prerequisite => have node and npm versions from obove ^
1. git clone this repo
2. cd into project
3. npm install
4. npm install gulp-cli -g (globally install gulp-cli to be able to run gulp)
5. run `gulp`

And then it throws this error:
```
gulp-browsersync git:(master) ✗ gulp                 
[23:05:26] Using gulpfile /var/www/projects/gulp-browsersync/gulpfile.js
[23:05:26] Starting 'default'...
[23:05:26] Starting 'scssTask'...
[23:05:26] 'scssTask' errored after 33 ms
[23:05:26] Error in plugin "gulp-postcss"
Message:
    EISDIR: illegal operation on a directory, read
Details:
    errno: -21
    code: EISDIR
    syscall: read
    fileName: /var/www/projects/gulp-browsersync/app/sass/style.css
    domainEmitter: [object Object]
    domainThrown: false

Stack:
Error: EISDIR: illegal operation on a directory, read
[23:05:26] 'default' errored after 35 ms

```

**Comment by thecodercoder** [comment]
Hi, the EISDIR error means that it was expecting to find a file but instead it is finding a directory. I'd double-check that the SCSS file in the src() part of the scssTask function exists and matches the file structure that you have in your project. The error you have is referencing a "app/sass" folder but in the default gulpfile in this repo it references "app/scss." Did you update your gulpfile to match your file/folder structure?

It's hard to know what the cause is without seeing your actual file/folder structure and what you have in your gulpfile. If you're still having this issue feel free to add what you are working with here.

**Comment by emilas44** [comment]
Indeed I had the wrong folder name... it was sass instead of scss
But now I renamed it and I still get the same error:
```
gulp
[08:24:12] Using gulpfile /var/www/projects/gulp-browsersync/gulpfile.js
[08:24:12] Starting 'default'...
[08:24:12] Starting 'scssTask'...
[08:24:12] 'scssTask' errored after 39 ms
[08:24:12] Error in plugin "gulp-postcss"
Message:
    EISDIR: illegal operation on a directory, read
Details:
    errno: -21
    code: EISDIR
    syscall: read
    fileName: /var/www/projects/gulp-browsersync/app/scss/style.css
    domainEmitter: [object Object]
    domainThrown: false

Stack:
Error: EISDIR: illegal operation on a directory, read
[08:24:12] 'default' errored after 41 ms
➜  gulp-browsersync git:(master) npm-v
zsh: command not found: npm-v
➜  gulp-browsersync git:(master) npm -v
6.14.11
➜  gulp-browsersync git:(master) node -v
v14.15.4
➜  gulp-browsersync git:(master) gulp -v
CLI version: 2.3.0

```

Here is my git repo: https://github.com/emilas44/gulp-browsersync/
Can you please check it out.

P.S. one more thing: When I just comment out this line of code inside gulpfile.js:
line 13 `.pipe(postcss([cssnano()]))`
then it compiles without error

**Comment by thecodercoder** [comment]
Ok, it does seem like the issue may be with gulp-postcss or cssnano. You could try posting an issue in the gulp-postcss repo.

I was able to run your repo's gulp task without error. I am using an old version of node (v8) so that could be why. Based on your title, was this ever working? Did it break after updating to node v14? If so then there may be an incompatibility issue with the newer version of node.

The cssnano will minify your CSS, so if it's not essential to minify CSS for what you're doing a temporary workaround could be to leave that line commented out so you can at least get it working.

**Comment by emilas44** [comment]
It never worked on this virtual machine... and now I created a new one and everything works.... it's just something wrong with I don't know what... never had this before :(

**Comment by thecodercoder** [comment]
That's weird! The issue may have been related to your VM in that case. Glad you got it working!
